<?php

require_once dirname(__FILE__) . '/../../../application/controllers/Index.php';

/**
 * Test class for IndexController.
 * Generated by PHPUnit on 2012-07-30 at 08:44:11.
 */
class IndexControllerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var IndexController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

//    /**
//     * @covers IndexController::init
//     * @todo Implement testInit().
//     */
//    public function testInit() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers IndexController::indexAction
//     * @todo Implement testIndexAction().
//     */
//    public function testIndexAction() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

}

?>
