<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset=utf-8>
        <title><?= (!empty($this->layout['meta_title']) ? $this->layout['meta_title'] : 'Teste com o Yaf');?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="keywords" content="">
        <meta name="description" content="">
        <meta name="robots" content="ALL">
        <meta name="distribution" content="Global">
        <meta name="rating" content="General">
        <meta name="author" content="">
        <meta name="language" content="pt-br">
        <meta name="doc-class" content="Completed">
        <meta name="doc-rights" content="Protected">
    </head>
    <body>
        <h1>Teste</h1>
        <div class="container">
            <?= $this->content ?>
        </div>
    </body>
</html>
